### ISSUE TITLE
fix app_pause() / app_resume()

### ISSUE THREAD

**Issue by catfact** [tehn/aleph#163]
these functions stop and start the app timers so that network data can be messed with. 

thhese functions are not good. 

mainly, they don't know when they are nested, so i suspect there are times when an inner function resumes prematurely and the parent function isn't aware.

if this isn't a bug yet, it easily could be.

avr32_lib/src/app.c

**Comment by ngwese** [comment]
This issue was duplicated by https://github.com/tehn/aleph/issues/221 (and the duplicate was addressed). Marking this as closed.
