### ISSUE TITLE
lines: buffer clearing causes init problems

### ISSUE THREAD

**Issue by catfact** [tehn/aleph#230]
parameters in lines do not become properly initialized if audio buffer is cleared (e.g. using memset() or per-sample loop) earlier in module_init().

https://github.com/tehn/aleph/blob/master/modules/lines/lines.c#L283

**Comment by ngwese** [comment]
I believe this fixes the problem.

https://github.com/tehn/aleph/pull/231

Not sure if it is the best solution. I tried reordering the the dsp module main() function - placing init_spi_slave() after module_init() but that didn't seem to work. slowing down the module boot sequence ultimately removed the asynchronous avr <=> bfin behavior which looks to be causing the problem.

**Comment by catfact** [comment]
that is exactly the right solution, the omission of wait_ready() there is a mistake.
