### ISSUE TITLE
DSP param read 

### ISSUE THREAD

**Issue by catfact** [tehn/aleph#246]
should create an operator to poll DSP params (or update on DSP callback, see #244 )

(from this discussion thread: http://llllllll.co/t/aleph-reading-dsp-params-in-bees/2311/10 )

to be useful, would require small hack to the inputs page to show param names for an input corresponding to param index:
https://github.com/tehn/aleph/blob/dev/apps/bees/src/pages/page_ins.c#L78

**Comment by ghost** [comment]
ok so initially I can try and get string display up & running for op_param.  Once that is done it should light the way how to improve grains' patch matrix...

**Comment by catfact** [comment]
as of 16080939a8e6d6ff2037e56c336c2cc5caa4b292 i'm calling this functional.
