### ISSUE TITLE
load bfin module over serial

### ISSUE THREAD

**Issue by ghost** [tehn/aleph#247]
Surely this must be possible now serial coms are up and running?

I can start to investigate feasibility from the serial comms side.  My thinking is initially try to somehow suspend bees, blast the entire module binary over the wire into avr32 memory, then back to host over the wire.  If the file comes back intact I'm guessing next step would be trivial (i.e load into the blackfin instead of return-to-sender).

bfin binaries are like 64K IIRC - is there enough spare RAM to fit the whole thing in avr32 memory at once?

**Comment by catfact** [comment]
Yeah. Shouldn't be a problem at all. When loading a module from sdcard, Bees allocates a temporary buffer from heap, fills it from the filesystem, blasts it over spi, and frees the buffer. (See `files_load_dsp_name ()`.) So doing it over serial would be almost identical.

**Comment by catfact** [comment]
Sorry, ```files_load_dsp_name ()```

**Comment by ghost** [comment]
first step towards this feature can be adding four new messages to serial protocol:
- bfin_prog_start (tell bees to allocate temporary buffers for bfin hex & dsc, zero fill pointers for these buffers & provide the module name)
- bfin_hex_chunk (send some chunk of hex data, up to 1kilobyte maybe, add that data to the bfin_hex temp buffer starting at fill-pointer, increment fill pointer by chunk length)
- bfin_dsc_chunk (send a chunk of dsc data, add that data to the bfin_dsc temp buffer starting at fill-pointer, increment fill pointer by chunk length)
- bfin_prog_end (tell bees to blast the contents of temp buffer over spi, load the descriptor, then free the buffers)

**Comment by ghost** [comment]
all the moving parts are in there now, apparently not in _quite_ the right order!

just trying that echo test now - figure out whether the hex actually survives it's journey...

**Comment by ghost** [comment]
Still somehow struggling to get everything to drop into place.  The good:
- hex survives a roundtrip intact
- think param-descriptor parse from buffer works (copied file-streaming version): https://github.com/rick-monster/aleph/blob/dev/apps/bees/src/files.c#L586
- bees comes back to life after the serial transmission, which is encouraging

The bad:
- after boot-over-serial blackfin is resolutely silent
- params don't seem to be getting initialised correctly (although descriptions, ranges & radix all look good)
- leads me to believe module_init may not be getting called over on the blackfin.  Is the thing booting correctly at all!?  As I said bees recovers after failed serial bfin boot - guessing those bfin_wait_ready would bring down the system if I was sending an unbootable program to the dsp!?

**Comment by catfact** [comment]
there's an explicit "enable audio" command, are you sending it?
https://github.com/rick-monster/aleph/blob/dev/apps/bees/src/scene.c#L375

.. hm, sorry, i guess that wouldn't explain initial parameters being screwy.

dumb question: when you say 'hex' you mean the .ldr file, right?

**Comment by ghost** [comment]
spotted that guy - I've been calling it here:

https://github.com/rick-monster/aleph/blob/dev/apps/bees/src/ser.c#L360

this function is my top-level blueprint:
https://github.com/rick-monster/aleph/blob/dev/apps/bees/src/pages/page_dsp.c#L156

**Comment by catfact** [comment]
hm, ok.

you know there are LEDs on the blackfin? they are white, on the bottom board, but you can actually see them flashing through the USB host port if you don't want to take the enclosure off.

e.g., you could

```
module_process_frame() {
static long int ledCount = 0;

  if(ledCount > 6000) {
    LED3_TOGGLE;
    LED4_TOGGLE;
    ledCount = 0;
  }
  ledCount++;
```

to see if the module is performing frame callbacks.

**Comment by catfact** [comment]
and yeah, i would think `bfin_wait_ready()` would stall the avr32 if bfin didn't boot (pin would stay low.)

**Comment by ghost** [comment]
Trying the LED thing right now - also added simple audio echo & testing now using the simple analyser module...

**Comment by ghost** [comment]
Can see the LED when loading from SD card. also double checked the actual checksum of returned hex file and all seems in order.  No LED activity or sound after serial load...

EDIT maybe I can get un-stuck here by also echoing the bfin prog back over serial port after read from sdcard - just in case there's an extra EOF byte or some other magic reason the hex could be getting corrupted...

**Comment by catfact** [comment]
gah, sorry, i can't spot anything wrong.

would test myself but i'd need a little help getting your `test-harness` running. 

i guess the next sanity check i'd do is calling `serial_bfinProgEcho` on the buffer that i get from the sdcard, and making sure it is identical to the buffer i get from serial load on the same .ldr.

**Comment by ghost** [comment]
contents of those two buffers are _totally_ different - so this is moving again - awesome!

I'll provide some instructions later on how to at least run my test harness - common lisp just has a weirdly steep learning curve at the start but awesome tool for this kind of testbench stuff.

The problem is that lisp (especially common lisp) doesn't want to do _anything_ the UNIX way, e.g no command line tools for package management - (obviously you should use lisp to manage lisp because linux sucks, right!?)...

**Comment by catfact** [comment]
sorry, i'm going to ask this really dumb question again- are you _sure_ you're sending `foo.ldr` over serial, and not the raw elf (just `foo`)?

**Comment by ghost** [comment]
Ok this was working but was blasting the wrong fscking file over the wire!

BINGO!  woooooooohoooo!

**Comment by ghost** [comment]
that was exactly it

**Comment by catfact** [comment]
:D

**Comment by ghost** [comment]
no more bees reboot cycle for module dev!!!!!

**Comment by catfact** [comment]
:clap:

**Comment by ghost** [comment]
right time to review & clean up a bit I was going crazy there for a minute hopefully didn't leave too much junk lying around...

**Comment by catfact** [comment]
ok, i'm gonna just try diving into the lisp stuff so i, too, can take advantage of this fantastic new technology called UART

**Comment by ghost** [comment]
right no sleep till the jack emulator is done!

**Comment by ghost** [comment]
to run my test harness in emacs (you're on linux, right?)
- install sbcl either from distro binary or source build is trivial: http://www.sbcl.org/
- install quicklisp https://www.quicklisp.org/beta/ (follow instructions from there)
- fire up lisp from terminal, execute these lisp commands:
  (load "quicklisp.lisp")
  (ql:add-to-init-file)
  (ql:quickload :quicklisp-slime-helper)
  (quicklisp-slime-helper:install)

then I think you're done - fire up emacs & M-x slime
- open the lisp file in utils on my branch, C-c C-k to compile and load into the running lisp
- make sure you have write permissions on that serial port, open it once in minicom, close again
- modify the paths in (defun test-bfin-module-load
- C-c C-k again to recompile that file into the running lisp
- run (start-debug-listener) in slime REPL (also sets raw transfer mode using stty from lisp so you have to do this first)
- run (test-bfin-module-load) in slime REPL - aleph should eventually come back up with new module running

**Comment by catfact** [comment]
cool thanks! 

i had to also `(ql:quickload "bordeaux-threads")` but after that everything seemed ok...

...until, unfortunately the aleph seems to have hung after `(test-bfin-module-load)`, which printed `19` in slime-repl and nothing in slime-compilation. 

also, disturbingly, aleph seems to hang at the startup glyph screen if the serial port is connected. will have to look into that. maybe just if some process is trying to talk to it.

i'm also running a release build (of your dev branch.) reflashing now with debug just to see.

anyways i'm actually done for the night, will come back to this tomorrow.

its been a little while since i dabbled in lisp/scheme, but i can see how this could be a pretty powerful environment. thanks for the push

**Comment by ghost** [comment]
ok so there's a secret spell I forgot.  I have these lines in ~/.swankrc 
`#+sbcl (setf swank:*communication-style* :spawn)`
`#+sbcl (defparameter swank:*globally-redirect-io* t)`
that's some config for lisp's emacs mode to make standard-output from background threads print to the slime-repl.  Kind of handy to make sure you see what is coming back from aleph.  Without this, debug output from the bg thread pops up in the buffer _inferior-lisp_

So probably a first step to make sure everything is set up good before blasting a whole module over maybe best to try this little ping first:

(serial-trigger-param stream 3 3)

or any of the other guys sitting in this function:
https://github.com/rick-monster/aleph/blob/dev/utils/serial-com-proto/test-harness.lisp#L354

In order to init the serial port properly after host reboot I seem to need to connect once only with minicom with the usual  minicom -b 115200 -D /dev/ttyACM0, then close minicom then this stty command is also necessary (bundled into starting the listener for some reason):
https://github.com/rick-monster/aleph/blob/dev/utils/serial-com-proto/test-harness.lisp#L345

I have tested only with release build (think it'll probs blow up with debug build) Also, assuming serial is working ok but bfin load explodes you can try decreasing the rate of data packets here:

https://github.com/rick-monster/aleph/blob/dev/utils/serial-com-proto/test-harness.lisp#L383

Also one more thing if the hex echo is uncommented here:

https://github.com/rick-monster/aleph/blob/dev/apps/bees/src/ser.c#L355

then the whole procedure sending & echo-ing back can take quite a few seconds.  I guess if you start tweaking encoders & stuff maybe the thing eventually wakes up with a full event queue and explodes.

**Comment by ghost** [comment]
ok so I tried the suggestion to suspend app timer interrupt during module load:

https://github.com/rick-monster/aleph/commit/db60e5fe18ed3db43ff14d0f4e6596c7e018fcaa

With that modification can send the bfin program at full tx speed (no calls to sleep required in host software).

**Comment by catfact** [comment]
awesome

**Comment by ghost** [comment]
gonna provide a simple C UNIX utility program for simple command-line bfin hotswap to complete this feature...

**Comment by ghost** [comment]
Hmm maybe should also overwrite the .ldr & dsc modules on sdcard on serial load?  Currently the module name is set to "serial".  So if you:
- load a module over serial
- set up a debug scene
- clean shutdown
- attempt boot

The device will hang on boot because it is looking for the module named "serial" on sdcard...

**Comment by ghost** [comment]
AFAIK this just works.  We can reopen the ticket if anyone reports a bug...
