### ISSUE TITLE
beekeep_juce segfaults on linux

### ISSUE THREAD

**Issue by ghost** [tehn/aleph#259]
here:

https://github.com/catfact/aleph/blob/dev/utils/beekeep_juce/JuceLibraryCode/modules/juce_events/native/juce_linux_Messaging.cpp#L129

Commenting those 2 lines results in a compile-able, running executable.  Don't know if it's actually doing anything though - I can drag boxes around the screen but can't connect wires between those boxes...

**Comment by catfact** [comment]
Sounds like expected behavior - haven't done connection gui yet. Found the crashing lines but didn't try just skipping them; I'd still like to find exactly what static init stuff in bees, is triggering the issue...

**Comment by ghost** [comment]
ok awesome so basically sounds like since this runs I should be able to use it to test what's turning into a pretty brutal refactor of op_life - pretty confident this thing will just randomly blow up on the aleph once the bull has left the chinashop...
