### ISSUE TITLE
Make monome grid come up cleanly on boot

### ISSUE THREAD

**Issue by ghost** [tehn/aleph#279]
Somehow a connected grid is not getting detected at boot time.  Looked to me that there might be some half-finished/reimplented-a-different-way shenanigans going on in this general area:

https://github.com/monome/aleph/blob/dev/avr32_lib/src/main.c#L96-L98
https://github.com/monome/aleph/blob/dev/avr32_lib/src/main.c#L105-L111

Ideally BEES will be aware there's a connected grid on boot, then immediately hand grid focus over according to scene data...

**Comment by boqs** [comment]
fixed in monome/dev now

**Comment by catfact** [comment]
💥
