### ISSUE TITLE
Create Param Scaler for Text Labels

### ISSUE THREAD

**Issue by ghost** [tehn/aleph#280]
For example grains' patch matrix needs this feature.  Added a new type of (optional) param descriptor file called a .lab - it's just a plain text file with one 'label' per line.

When you use the new 'patchmatrix' param datatype, the play screen & ins screen display the text value, not the numerical index.  Feature is basically working...

TODO:
- [x] clean up debug etc
- [x] figure out why grains' param descriptor seems borked w/ new feature
- [x] probably rename everything to label - 'patch matrix' is only one possible use of this feature
- [x] fix a bug where the last label string is corrupted (probably missing \0)

**Comment by boqs** [comment]
this has been merged to dev now - we could close this (and quite a few other issues) I think - declutter things a bit in here!

**Comment by catfact** [comment]
🎉
