### ISSUE TITLE
using bfin for graphics

### ISSUE THREAD

**Issue by electropourlaction** [tehn/aleph#284]
I'm curious about exploring the bfin processor for graphics, and to find out what work that would need to be done. 

could the avr32 be a big bottleneck, assuming that it would need to receive data from bfin via spi and make it available to one of it's available outputs?

what would be a short list of thing to do to make a function test, like a graphic primitive output to an external screen/vga?

**Comment by lazzarello** [comment]
From the data sheet for the BF533

> Full SIMD architecture, including instructions for accelerated video and image processing

http://www.analog.com/en/products/processors-dsp/blackfin/adsp-bf533.html#product-overview

**Comment by catfact** [comment]
yeah i just don't know how you would go about this with the aleph hardware configuration. as you say, bfin has no connection to the outside world except the audio IO and cv outs. these don't have the high-speed clocks necessary for analog video (though you could get a functional alpha channel i think.)

as far as producing graphics on bfin, sending them back to avr32 via spi, and thence to some kind of video connector... i don't know? maybe hack some kind of USB->VGA connection? it would get freaky - again you don't have anything like a 25Mhz timer for the pixel clock, but i think you could hack some kind of [legacy text mode](https://en.wikipedia.org/wiki/VGA-compatible_text_mode). could be an interesting project but way outside of the use cases we had in mind!

@electropourlaction if you don't mind i'm gonna close this as an aleph issue.

**Comment by electropourlaction** [comment]
I don't mind, and now with some time to get me past the initial frenzy of the idea, sort of a relief actually.
