### ISSUE TITLE
bees: scene <-> module name checks are broken

### ISSUE THREAD

**Issue by catfact** [tehn/aleph#80]
need to update current-scene descriptor on module load, etc

**Comment by ngwese** [comment]
i've been poking at stuff in this area and also noticed this related issue:
https://github.com/tehn/aleph/issues/233

in handling the other issue i'll verify that the current logic is more or less optimal given the variability of module names in old scenes

**Comment by catfact** [comment]
all looks fine to me.
i should point out that it's perfectly straightforward to go in with a hex editor and just change the module-name string in a given older .scn file (or use beekeep and edit the JSON), if this is ever necessary

**Comment by catfact** [comment]
i think this is fixed:
https://github.com/tehn/aleph/blob/dev/apps/bees/src/scene.c#L250
